title: Germán Ruiz Mudarra
description: > 
Electronics, Robotics and Mechatronics Engineer. M.Sc. in Mechatronics Engineering. # add description
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://gruizmudarra.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Germán Ruiz Mudarra # add your name
author-img: german-ruiz.jpg # add your photo
about-author: Electronics, Robotics and Mechatronics Engineer. M.Sc. in Mechatronics Engineering. # add description
social-github: gruizmudarra # add your Github handle
social-linkedin: gruizmudarra # add your Linkedin handle
social-email: germanruizmudarra@gmail.com # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
