# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist

# Setup
title:            Germán Ruiz Mudarra
tagline:          'My Portfolio'
description:      'Robotics and Mechatronics Engineer.'
url:              http://gruizmudarra.github.io
baseurl:          /

author:
  name:           'Germán Ruiz Mudarra'
  url:             https://github.com/gruizmudarra

social-github: gruizmudarra # add your Github handle
social-linkedin: gruizmudarra # add your Linkedin handle
social-email: germanruizmudarra@gmail.com # add your Email address

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/gruizmudarra/gruizmudarra.github.io
